### ISSUE TITLE
require('cfx') changes working directory

### ISSUE THREAD

**Issue by peacememories** [jsantell/node-cfx#3]
What it says in the title.
Unexpected behaviour that I don't think should happen, but _at least_ needs to be documented.

**Comment by peacememories** [comment]
Deleting the cwd call doesn't seem to have any negative consequences. Why is it there?

**Comment by jsantell** [comment]
We're currently deprecating cfx in favor of [jpm](https://github.com/mozilla/jpm) ([blog post](https://blog.mozilla.org/addons/2015/02/26/jpm-replaces-cfx-for-firefox-38/)) -- I just gave you repo access to node-cfx though so you're not held up by me :) merge away!

**Comment by peacememories** [comment]
Yeah I know, but until the current firefox release supports it I guess I'm stuck with cfx^^. Thanks for the access, though I do hope I'm not ruining a perfectly good codebase. Not a seasoned foss contributor here.

**Comment by jsantell** [comment]
FWIW, I don't think many people other than myself previously were using this, and @PixnBits was just recently working on it for [gulp-cfx-xpi](https://github.com/PixnBits/gulp-cfx-xpi) -- I'll give them access as well

**Comment by jsantell** [comment]
@PixnBits @peacememories let me know your npm names if you want publish access as well

**Comment by PixnBits** [comment]
related to PR #6
